// Generated by gencpp from file atv_can/DriveService.msg
// DO NOT EDIT!


#ifndef ATV_CAN_MESSAGE_DRIVESERVICE_H
#define ATV_CAN_MESSAGE_DRIVESERVICE_H

#include <ros/service_traits.h>


#include <atv_can/DriveServiceRequest.h>
#include <atv_can/DriveServiceResponse.h>


namespace atv_can
{

struct DriveService
{

typedef DriveServiceRequest Request;
typedef DriveServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveService
} // namespace atv_can


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atv_can::DriveService > {
  static const char* value()
  {
    return "c25d42b04dddc79f7f5281624f435ed8";
  }

  static const char* value(const ::atv_can::DriveService&) { return value(); }
};

template<>
struct DataType< ::atv_can::DriveService > {
  static const char* value()
  {
    return "atv_can/DriveService";
  }

  static const char* value(const ::atv_can::DriveService&) { return value(); }
};


// service_traits::MD5Sum< ::atv_can::DriveServiceRequest> should match 
// service_traits::MD5Sum< ::atv_can::DriveService > 
template<>
struct MD5Sum< ::atv_can::DriveServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atv_can::DriveService >::value();
  }
  static const char* value(const ::atv_can::DriveServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atv_can::DriveServiceRequest> should match 
// service_traits::DataType< ::atv_can::DriveService > 
template<>
struct DataType< ::atv_can::DriveServiceRequest>
{
  static const char* value()
  {
    return DataType< ::atv_can::DriveService >::value();
  }
  static const char* value(const ::atv_can::DriveServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atv_can::DriveServiceResponse> should match 
// service_traits::MD5Sum< ::atv_can::DriveService > 
template<>
struct MD5Sum< ::atv_can::DriveServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atv_can::DriveService >::value();
  }
  static const char* value(const ::atv_can::DriveServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atv_can::DriveServiceResponse> should match 
// service_traits::DataType< ::atv_can::DriveService > 
template<>
struct DataType< ::atv_can::DriveServiceResponse>
{
  static const char* value()
  {
    return DataType< ::atv_can::DriveService >::value();
  }
  static const char* value(const ::atv_can::DriveServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATV_CAN_MESSAGE_DRIVESERVICE_H
