// Generated by gencpp from file atv_can/SteeringMeasurement.msg
// DO NOT EDIT!


#ifndef ATV_CAN_MESSAGE_STEERINGMEASUREMENT_H
#define ATV_CAN_MESSAGE_STEERINGMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atv_can
{
template <class ContainerAllocator>
struct SteeringMeasurement_
{
  typedef SteeringMeasurement_<ContainerAllocator> Type;

  SteeringMeasurement_()
    : encoder_position(0)
    , time_received()  {
    }
  SteeringMeasurement_(const ContainerAllocator& _alloc)
    : encoder_position(0)
    , time_received()  {
  (void)_alloc;
    }



   typedef uint32_t _encoder_position_type;
  _encoder_position_type encoder_position;

   typedef ros::Time _time_received_type;
  _time_received_type time_received;




  typedef boost::shared_ptr< ::atv_can::SteeringMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atv_can::SteeringMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct SteeringMeasurement_

typedef ::atv_can::SteeringMeasurement_<std::allocator<void> > SteeringMeasurement;

typedef boost::shared_ptr< ::atv_can::SteeringMeasurement > SteeringMeasurementPtr;
typedef boost::shared_ptr< ::atv_can::SteeringMeasurement const> SteeringMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atv_can::SteeringMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atv_can::SteeringMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace atv_can

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'atv_can': ['/home/atv/atv-project-2017/catkin_ws/src/atv_can/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atv_can::SteeringMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atv_can::SteeringMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atv_can::SteeringMeasurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ea82a2a633f2b7c6b3360bca5c4c3ea";
  }

  static const char* value(const ::atv_can::SteeringMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ea82a2a633f2b7cULL;
  static const uint64_t static_value2 = 0x6b3360bca5c4c3eaULL;
};

template<class ContainerAllocator>
struct DataType< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atv_can/SteeringMeasurement";
  }

  static const char* value(const ::atv_can::SteeringMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 encoder_position\n\
time time_received\n\
";
  }

  static const char* value(const ::atv_can::SteeringMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder_position);
      stream.next(m.time_received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteeringMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atv_can::SteeringMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atv_can::SteeringMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "encoder_position: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_position);
    s << indent << "time_received: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATV_CAN_MESSAGE_STEERINGMEASUREMENT_H
