(cl:in-package gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEQ-VAL
          SEQ
          STAMP-VAL
          STAMP
          FRAME_ID-VAL
          FRAME_ID
          GPS_ID-VAL
          GPS_ID
          GPS_TIME-VAL
          GPS_TIME
          NUM_OBS-VAL
          NUM_OBS
          L1-VAL
          L1
          L2-VAL
          L2
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          LAT_COV-VAL
          LAT_COV
          LON_COV-VAL
          LON_COV
          ALT_COV-VAL
          ALT_COV
))