(cl:in-package gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEQ-VAL
          SEQ
          STAMP-VAL
          STAMP
          FRAME_ID-VAL
          FRAME_ID
          GPS_ID_FROM-VAL
          GPS_ID_FROM
          GPS_ID_TO-VAL
          GPS_ID_TO
          GPS_TIME-VAL
          GPS_TIME
          STATUS-VAL
          STATUS
          RATIO-VAL
          RATIO
          INPUT_OBS-VAL
          INPUT_OBS
          NON_FAULT_OBS-VAL
          NON_FAULT_OBS
          AMB_OBS-VAL
          AMB_OBS
          SP-VAL
          SP
          LP-VAL
          LP
          HP-VAL
          HP
          BASE_PRN_FLOAT-VAL
          BASE_PRN_FLOAT
          BASE_PRN_FIXED-VAL
          BASE_PRN_FIXED
))