(cl:in-package gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEQ-VAL
          SEQ
          STAMP-VAL
          STAMP
          FRAME_ID-VAL
          FRAME_ID
          GPS_ID-VAL
          GPS_ID
          GPS_TIME-VAL
          GPS_TIME
          OBS-VAL
          OBS
          PRN-VAL
          PRN
          HEALTH-VAL
          HEALTH
          SEMIMAJOR_AXIS-VAL
          SEMIMAJOR_AXIS
          MEAN_ANOMALY-VAL
          MEAN_ANOMALY
          ECCENTRICITY-VAL
          ECCENTRICITY
          PERIGEE_ARG-VAL
          PERIGEE_ARG
          COS_LATITUDE-VAL
          COS_LATITUDE
          SIN_LATITUDE-VAL
          SIN_LATITUDE
          COS_ORBIT_RADIUS-VAL
          COS_ORBIT_RADIUS
          SIN_ORBIT_RADIUS-VAL
          SIN_ORBIT_RADIUS
          COS_INCLINATION-VAL
          COS_INCLINATION
          SIN_INCLINATION-VAL
          SIN_INCLINATION
          INCLINATION_ANGLE-VAL
          INCLINATION_ANGLE
          RIGHT_ASCENSION-VAL
          RIGHT_ASCENSION
          MEAN_MOTION_DIFF-VAL
          MEAN_MOTION_DIFF
          INCLINATION_RATE-VAL
          INCLINATION_RATE
          ASCENSION_RATE-VAL
          ASCENSION_RATE
          TIME_OF_WEEK-VAL
          TIME_OF_WEEK
          REFERENCE_TIME-VAL
          REFERENCE_TIME
          CLOCK_CORRECTION-VAL
          CLOCK_CORRECTION
          GROUP_DELAY-VAL
          GROUP_DELAY
          CLOCK_AGING_1-VAL
          CLOCK_AGING_1
          CLOCK_AGING_2-VAL
          CLOCK_AGING_2
          CLOCK_AGING_3-VAL
          CLOCK_AGING_3
))