# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from atv_can/OdometryMeasurement.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class OdometryMeasurement(genpy.Message):
  _md5sum = "ee02656794889f6c998dfdb92a35704d"
  _type = "atv_can/OdometryMeasurement"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 front_left
int16 front_right
int16 rear_left
int16 rear_right
time time_received
"""
  __slots__ = ['front_left','front_right','rear_left','rear_right','time_received']
  _slot_types = ['int16','int16','int16','int16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       front_left,front_right,rear_left,rear_right,time_received

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OdometryMeasurement, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.front_left is None:
        self.front_left = 0
      if self.front_right is None:
        self.front_right = 0
      if self.rear_left is None:
        self.rear_left = 0
      if self.rear_right is None:
        self.rear_right = 0
      if self.time_received is None:
        self.time_received = genpy.Time()
    else:
      self.front_left = 0
      self.front_right = 0
      self.rear_left = 0
      self.rear_right = 0
      self.time_received = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4h2I.pack(_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.time_received.secs, _x.time_received.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time_received is None:
        self.time_received = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.time_received.secs, _x.time_received.nsecs,) = _struct_4h2I.unpack(str[start:end])
      self.time_received.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4h2I.pack(_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.time_received.secs, _x.time_received.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time_received is None:
        self.time_received = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.time_received.secs, _x.time_received.nsecs,) = _struct_4h2I.unpack(str[start:end])
      self.time_received.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4h2I = struct.Struct("<4h2I")
