(cl:defpackage atv_can-msg
  (:use )
  (:export
   "<ODOMETRYMEASUREMENT>"
   "ODOMETRYMEASUREMENT"
   "<DASHGASPEDALMEASUREMENT>"
   "DASHGASPEDALMEASUREMENT"
   "<STEERINGMEASUREMENT>"
   "STEERINGMEASUREMENT"
  ))

